#ifndef QTINITPROJLIB_GLOBAL_H
#define QTINITPROJLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTINITPROJLIB_LIBRARY)
#  define QTINITPROJLIB_EXPORT Q_DECL_EXPORT
#else
#  define QTINITPROJLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // QTINITPROJLIB_GLOBAL_H
